# #################################
# Data Definition
# #################################
# Where does your milk come from?
# #################################
---
DataSources:
  elmo: pizza
  saulDataSource:
    -
      name     : SQLITE_TEST
      url      : jdbc:sqlite:TEST.db
      username :
      password :
      driver-class-name: org.sqlite.JDBC
    -
      name     : SQLITE_TEST2
      url      : jdbc:sqlite:TEST.db2
      username :
      password :
      driver-class-name: org.sqlite.JDBC



#      database:
#        name: Johnson

#---
#SaulDataDefinitions:
#  dataDefinition:
#    - identity :
#        source     : TD
#        name       : TD_ALERT
#        shortName  : TD_ALERT
#      dataSource : TD_ORACLE
#      #cache       :
#      #  durationTime : 10
#      #  durationType : minutes
#      fields :
#        - column     : Td_Alert_Id
#          alias      : Alert_Id
#          dataType   : long
#      sql : |
#        SELECT  Td_Alert_Id
#        FROM    TDDATA.TD_ALERT
#        WHERE   ROWNUM <= :count:
#        AND     Pizza = :pie:
#
#- identity    :
#    source      : TD
#    name        : MILK_TABLE
#    short_name  : MILK_TABLE
#  data_source : TD_ORACLE
#  cache       :
#    duration_time : 10
#    duration_type : minutes
#  fields :
#    - column      : id
#      alias       : milk_id
#      data_type   : long
#    - column      : source
#      alias       : milk_source
#      data_type   : varchar
#      data_length : 32
#    - column      : milked_date
#      alias       : milked_date
#      data_type   : datetime
#    - column      : amount_in_gallons
#      alias       : amount_in_gallons
#      data_type   : integer
#  sql : |
#    SELECT  id
#    ,       source
#    ,       milked_date
#    ,       amount_in_gallons
#    FROM    MILK_TABLE
